git checkout -b let packages install on CentOS
irods/irods_microservice_plugins_curl pull request #49
Opened 2022-05-31 00:45 UTC by d-w-moore

add CPACK_RPM_EXCLUDE_FROM_AUTO_FILELIST_ADDITION to avoid package file conflicts with iRODS packages and allow centos7 tests to pass for 4.3.0 release

2022-06-01 14:50 UTC, SwooshyCueb requested changes

2022-06-01 14:50 UTC, SwooshyCueb commented on CMakeLists.txt
> +list(APPEND CPACK_RPM_EXCLUDE_FROM_AUTO_FILELIST_ADDITION "${CPACK_PACKAGING_INSTALL_PREFIX}var/lib/irods/scripts/irods/test")
Please follow the pattern from the python repo:
https://github.com/irods/irods_rule_engine_plugin_python/blob/8f7356e499e60a4e55475506b0078a02d115f842/CMakeLists.txt#L128-L131

2022-06-03 14:53 UTC, SwooshyCueb commented on CMakeLists.txt
> +endif()
I'm fairly certain this isn't needed either way. Try a clean build without this bit and see if the rpms come out okay

2022-06-03 14:54 UTC, d-w-moore commented on CMakeLists.txt
> +endif()
Will do.

2022-06-06 16:12 UTC, d-w-moore commented
squashed/#'d

2022-06-06 17:41 UTC, alanking approved these changes

2022-06-06 17:41 UTC, merged